version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media:

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: irabrosimov/foodgram:latest
    restart: always
    volumes:
      - static_volume:/code/static/
      - media:/code/media
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.0
    volumes:
      - media:/code/media
      - static_volume:/code/static/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web