# Generated by Django 2.2 on 2021-01-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='recipe',
        ),
        migrations.AddField(
            model_name='favorites',
            name='recipe',
            field=models.ManyToManyField(related_name='favorites', to='recipes.Recipe', verbose_name='Избранное'),
        ),
    ]
