# Generated by Django 2.2 on 2021-02-16 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorite_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_recipes', through='recipes.Favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='purchase_by',
            field=models.ManyToManyField(blank=True, related_name='shop_list', through='recipes.ShopList', to=settings.AUTH_USER_MODEL),
        ),
    ]
