# Generated by Django 2.2 on 2021-03-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210216_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название продукта'),
        ),
    ]
