# Generated by Django 2.2 on 2021-03-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210304_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
